### ISSUE TITLE
Context-menu inaccessible at the end of the browser window

### ISSUE THREAD

**Issue by YogeshPrasanna** [karthikJagadeesh/scheduler-prototype#1]
_Check the below screenshot_

![screenshot 46](https://cloud.githubusercontent.com/assets/18151732/21926051/2358d370-d9a6-11e6-8504-a1c2ea2052df.png)

**Comment by karthikJagadeesh** [comment]
Fixed by vignesh

**Comment by YogeshPrasanna** [comment]
_Issue still exists ! calendar isn't displayed completely_

![screenshot 47](https://cloud.githubusercontent.com/assets/18151732/21928489/1e9db6d8-d9b1-11e6-9fb5-c6c2f2c2dc5a.png)

**Comment by YogeshPrasanna** [comment]
Madalla hogo
